#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gdal
Version  : 3.4.3
Release  : 65
URL      : http://download.osgeo.org/gdal/3.4.3/gdal-3.4.3.tar.xz
Source0  : http://download.osgeo.org/gdal/3.4.3/gdal-3.4.3.tar.xz
Summary  : Geospatial Data Abstraction Library
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause ISC LGPL-2.0 Libpng MIT Public-Domain Qhull
BuildRequires : SFCGAL-dev
BuildRequires : buildreq-cpan
BuildRequires : buildreq-distutils3
BuildRequires : curl-dev
BuildRequires : expat-dev
BuildRequires : geos-dev
BuildRequires : giflib-dev
BuildRequires : hdf5-dev
BuildRequires : json-c-dev
BuildRequires : libgeotiff-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev
BuildRequires : libwebp-dev
BuildRequires : ocl-icd-dev
BuildRequires : openssl-dev
BuildRequires : pcre-dev
BuildRequires : pcre2-dev
BuildRequires : pkgconfig(OpenEXR)
BuildRequires : pkgconfig(libpq)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(poppler)
BuildRequires : pkgconfig(spatialite)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : proj
BuildRequires : proj-dev
BuildRequires : qhull-dev
BuildRequires : tiff-dev
BuildRequires : unixODBC-dev
BuildRequires : xerces-c-dev
BuildRequires : zstd-dev

%description
The following source files are taken from the HDF-EOS package
EHapi.c,
GDapi.c,
SWapi.c,
HDFEOSVersion.h,
HdfEosDef.h,
ease.h

%prep
%setup -q -n gdal-3.4.3
cd %{_builddir}/gdal-3.4.3
pushd ..
cp -a gdal-3.4.3 buildavx2
popd

%build
## build_prepend content
sed -i 's/-flto"$/-flto=auto"/' ./configure.ac
# Also patch the generated configure script, in case we stop patching
# configure.ac, m4 files, etc.
sed -i 's/-flto"$/-flto=auto"/' ./configure
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1664892855
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mprefer-vector-width=256 "
export FCFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mprefer-vector-width=256 "
export FFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mprefer-vector-width=256 "
export CXXFLAGS="$CXXFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mprefer-vector-width=256 "
%configure --disable-static --with-libtiff=yes \
--with-png=yes \
--with-spatialite=yes \
--with-sqlite3=yes \
--with-poppler=yes \
--enable-lto \
--with-gif=/usr \
--with-libjson-c=/usr \
--with-libtool=yes
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
## build_prepend content
sed -i 's/-flto"$/-flto=auto"/' ./configure.ac
# Also patch the generated configure script, in case we stop patching
# configure.ac, m4 files, etc.
sed -i 's/-flto"$/-flto=auto"/' ./configure
## build_prepend end
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static --with-libtiff=yes \
--with-png=yes \
--with-spatialite=yes \
--with-sqlite3=yes \
--with-poppler=yes \
--enable-lto \
--with-gif=/usr \
--with-libjson-c=/usr \
--with-libtool=yes
make  %{?_smp_mflags}
popd
%install
export SOURCE_DATE_EPOCH=1664892855
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gdal
cp %{_builddir}/gdal-%{version}/LICENSE.TXT %{buildroot}/usr/share/package-licenses/gdal/3c5056c99522acf3d9e2c2a2f61fdeeffced4174 || :
cp %{_builddir}/gdal-%{version}/alg/internal_libqhull/COPYING.txt %{buildroot}/usr/share/package-licenses/gdal/baf1d15dcf66b1e1dfee80eb405aa73105842017 || :
cp %{_builddir}/gdal-%{version}/doc/source/gdal_rtd/LICENSE %{buildroot}/usr/share/package-licenses/gdal/8ce271d47d282a4da574b385a8aff7a0d735188e || :
cp %{_builddir}/gdal-%{version}/doc/source/license.rst %{buildroot}/usr/share/package-licenses/gdal/0f9d62383e84298877fe5f5d41f6a944f7ef8563 || :
cp %{_builddir}/gdal-%{version}/frmts/gif/giflib/COPYING %{buildroot}/usr/share/package-licenses/gdal/f9c9a2d3495a0766b4cf20d4b90cfe714dab3dc1 || :
cp %{_builddir}/gdal-%{version}/frmts/mrf/LERCV1/LICENSE.TXT %{buildroot}/usr/share/package-licenses/gdal/3035b519169390d1aaa3a43267deaae5cdff8a9b || :
cp %{_builddir}/gdal-%{version}/frmts/pcraster/libcsf/COPYING %{buildroot}/usr/share/package-licenses/gdal/1d982db70b88f943cc7d15013c28a126339d6cbc || :
cp %{_builddir}/gdal-%{version}/frmts/png/libpng/LICENSE %{buildroot}/usr/share/package-licenses/gdal/fc3951ba26fe1914759f605696a1d23e3b41766f || :
cp %{_builddir}/gdal-%{version}/ogr/ogrsf_frmts/flatgeobuf/LICENSE %{buildroot}/usr/share/package-licenses/gdal/161732baff9a38188301a521b567a20245367c7e || :
cp %{_builddir}/gdal-%{version}/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/LICENSE %{buildroot}/usr/share/package-licenses/gdal/abb8eb20f7f319cd8b292cdccce15826bac01363 || :
cp %{_builddir}/gdal-%{version}/ogr/ogrsf_frmts/geojson/libjson/COPYING %{buildroot}/usr/share/package-licenses/gdal/0cd23537e3c32497c7b87157b36f9d2eb5fca64b || :
cp %{_builddir}/gdal-%{version}/ogr/ogrsf_frmts/shape/COPYING %{buildroot}/usr/share/package-licenses/gdal/df97bdf33b01f9ed42a799dd3ed7a1599dd0cb9d || :
cp %{_builddir}/gdal-%{version}/port/LICENCE_minizip %{buildroot}/usr/share/package-licenses/gdal/f7f1d88d0aea6c567a2c351b08b0fe80f2582054 || :
cp %{_builddir}/gdal-%{version}/third_party/LercLib/LICENSE %{buildroot}/usr/share/package-licenses/gdal/3035b519169390d1aaa3a43267deaae5cdff8a9b || :
cp %{_builddir}/gdal-%{version}/third_party/LercLib/NOTICE %{buildroot}/usr/share/package-licenses/gdal/4e8e03579f57bab9de5401be3fb96344f0823ead || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/etc/bash_completion.d/gdal-bash-completion.sh
## install_append content
#install -D %{buildroot}/usr/etc/bash_completion.d/gdal-bash-completion.sh %{buildroot}/usr/share/bash-completion/completions/gdal-bash-completion.sh
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
